In [2]:
import numpy as np

In [3]:
# как создать вектор?


In [4]:
# как одномерный массив numpy
a=np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [5]:
np.array([1,2,3], dtype='float')

array([1., 2., 3.])

In [6]:
# преобразовать из списка (list)
x=[1,2,3]
x_arr=np.array(x)
print(x, type(x))
print(x_arr, type(x_arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [7]:
# нулевой вектор
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [8]:
# вектор из единиц
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# массив чисел по порядку
np.arange(10,50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
# случайный вектор
np.random.randint(-4, 2, 10) # dim=10, случаные целые числа от -4 до 2

array([-3,  1, -1, -4, -2, -1, -4,  1, -3,  0])

In [11]:
# преобразовать из Pandas Series
import pandas as pd
data = [65, 70, 120, 35]
s = pd.Series(data)
print('Series:\n',s)

Series:
 0     65
1     70
2    120
3     35
dtype: int64


In [12]:
x = s.values # возвращает значения s
print('vector:\n',x)
print('type of x:',type(x))

vector:
 [ 65  70 120  35]
type of x: <class 'numpy.ndarray'>


In [13]:
# преобразовать из Pandas DataFrame
d = {'$$': [65, 70, 120, 35], '2.Area': [50, 52, 80, 33],'3.Rooms':[3,2,1,1], 
     '4.Floor':[5,12,10,3], '5.Demo':[8,4,5,10]}
df = pd.DataFrame(d)
print('Data Frame:\n',df)

Data Frame:
     $$  2.Area  3.Rooms  4.Floor  5.Demo
0   65      50        3        5       8
1   70      52        2       12       4
2  120      80        1       10       5
3   35      33        1        3      10


In [14]:
A = df.values # возвращает значения df
print('Matrix:\n',A)

Matrix:
 [[ 65  50   3   5   8]
 [ 70  52   2  12   4]
 [120  80   1  10   5]
 [ 35  33   1   3  10]]


In [15]:
x=A[1] # вторая строка матрицы А
print('Second apartment vector:\n',x)
print('type of x:',type(x))

Second apartment vector:
 [70 52  2 12  4]
type of x: <class 'numpy.ndarray'>


In [16]:
y=A[:,0] # первый столбец матрицы А
print('$$ vector:\n',y)

$$ vector:
 [ 65  70 120  35]


In [17]:
# индексация векторов - поиск нужной координаты
print('$$ of 3 apartment:',y[2]) # третья координата

$$ of 3 apartment: 120


In [18]:
# размерность вектора
print('Number of apartments = dim(y):', len(y))

Number of apartments = dim(y): 4


In [19]:
# сумма векторов и умножение на число
a=np.array([1,2,3])
b=np.array([6,7,8])
print('a+b:',a+b)
print('2a:',2*a)

a+b: [ 7  9 11]
2a: [2 4 6]


In [20]:
# сумма списков и умножение на число не является векторной операцией!
a_list=[1,2,3]
b_list=[6,7,8]
print('a+b:',a_list+b_list)
print('2a:',2*a_list)

a+b: [1, 2, 3, 6, 7, 8]
2a: [1, 2, 3, 1, 2, 3]


In [21]:
# линейная комбинация с коэффициентами 2, 2, 3
a=np.array([1,2,3])
b=np.array([6,7,8])
c=np.array([1,0,1])

d=2*a+2*b+3*c
print('linear combination:',d)

linear combination: [17 18 25]


In [22]:
# скалярное произведение

s=np.dot(a,b)
print('scalar product:',s)

# покоординатное умножение
print('coordinate product:',a*b)

scalar product: 44
coordinate product: [ 6 14 24]


In [23]:
# скалярное произведение - еще один способ
s1=a@b
print('scalar product:',s1)

scalar product: 44


In [24]:
# длина вектора
l=np.linalg.norm(a)
print('length of a:',l)

length of a: 3.7416573867739413


In [25]:
# нормировка
a_norm=a/np.linalg.norm(a)
print('a_norm:',a_norm)
print('length of a_norm:',np.linalg.norm(a_norm))

a_norm: [0.26726124 0.53452248 0.80178373]
length of a_norm: 1.0


In [26]:
#пропорциональность и ортогональность
a=np.array([1,2,1])
b=a*2
c=np.array([-1,1,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 2 1]
b: [2 4 2]
c: [-1  1 -1]


In [27]:
#пропорциональность и ортогональность
print("(a,b):",np.dot(a,b))
print("(a,c):",np.dot(a,c))
print("(b,c):",np.dot(b,c))

(a,b): 12
(a,c): 0
(b,c): 0


In [28]:
# попарная ортогональность - да
a=np.array([1,0,1])
b=np.array([0,1,0])
c=np.array([1,0,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 0 1]
b: [0 1 0]
c: [ 1  0 -1]


In [29]:
# попарная ортогональность - да
print('(a,b):',np.dot(a,b))
print('(b,c):',np.dot(b,c))
print('(a,c):',np.dot(a,c))

(a,b): 0
(b,c): 0
(a,c): 0


In [30]:
# попарная ортогональность - нет
c1=np.array([1,0,4])
print('a:',a)
print('b:',b)
print('с1:',c1)

a: [1 0 1]
b: [0 1 0]
с1: [1 0 4]


In [31]:
# попарная ортогональность - нет
print('(a,b):',a@b)
print('(b,c1):',b@c1)
print('(a,c1):',a@c1)

(a,b): 0
(b,c1): 0
(a,c1): 5


In [32]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85],
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65],
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5],
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10],
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
print('DF: ', Hut_Paradise_DF)

DF:     1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40


In [33]:
matrix = Hut_Paradise_DF.values
print('Matrix:\n',matrix)

Matrix:
 [[ 65  50   3   5   8  37]
 [ 70  52   2  12   4  40]
 [120  80   1  10   5  65]
 [ 35  33   1   3  10  20]
 [ 40  33   1   6  20  16]
 [ 50  44   2  13  12  35]
 [100  80   4   8   5  60]
 [ 90  65   3  21   1  50]
 [ 85  65   2   5  10  40]]


In [34]:
matrix[4]

array([40, 33,  1,  6, 20, 16])

In [35]:
matrix[:, 1] - matrix[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [36]:
a = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
a@matrix[:, 4]

np.int64(1348)

In [37]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [38]:
n = 2*v + -3*w
n

array([-3, 14,  3,  4,  2])

In [39]:
n@u

np.int64(0)

In [49]:
from sklearn.preprocessing import PolynomialFeatures

x = np.array([[1, 3, -2, 9]]).T
y = np.array([3, 7, -5, 21])
poly = PolynomialFeatures(degree=2, include_bias=True)
poly_x = poly.fit_transform(x)
w_hat = np.linalg.inv(poly_x.T@poly_x)@poly_x.T@y
w_hat

array([ 0.11446013,  2.46095638, -0.01608801])

In [57]:
from sklearn.linear_model import Ridge

x0 = np.ones(5)
x1 = [5, 9, 4, 3, 5]
x2 = [15, 18, 18, 19, 19]
x3 = [7, 6, 7, 7, 7]
y = np.array([24, 22, 35, 33, 36])

alpha = 1

X = np.array([x0, x1, x2, x3]).T

model = Ridge(alpha=alpha, fit_intercept=False)
model.fit(X, y)
print(model.coef_)

[-0.08523045 -1.70784126  1.91141216  0.7293992 ]
